Swoletrics/swoletrics/models.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from swoletrics import db


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    # routine = db.relationship('Routine', backref='user', lazy='dynamic')
    password_hash = db.Column(db.String)

    @property
    def password(self):
        raise AttributeError('password: write-only field')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()

    def __repr__(self):
        return f"<User '{self.username}'>"

Swoletrics/swoletrics/routines/models.py
from swoletrics import db
from typing import List
from datetime import datetime


class Set(db.model):
    __tablename__ = "sets"
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True)

    def __init__(self, reps: int, weight: float):
        self.reps = reps
        self.weight = weight

    def __str__(self):
        return f"{self.weight} x {self.reps}"


exercise_set = db.Table('exercise_set',
                        db.Column('set_id', db.Integer, db.ForeignKey('set.id'), primary_key=True),
                        db.Column('exercise_id', db.Integer, db.ForeignKey('exercise.id'), primary_key=True)
                        )


class Exercise(db.model):
    __tablename__ = "exercises"
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True)
    sets = db.relationship('Sets', secondary=exercise_set, lazy='subquery',
                           backref=db.backref('exercises', lazy=True)
                           )

    def __init__(self, name: str, date: datetime, sets: List[Set] = None, body_parts: List[str] = None):
        self.name = name
        self.date = date
        self.body_parts = body_parts
        self.sets = sets


workout_exercise = db.Table('workout_exercise',
                            db.Column('exercise_id', db.Integer, db.ForeignKey('exercise.id'), primary_key=True),
                            db.Column('workout_id', db.Integer, db.ForeignKey('workout.id'), primary_key=True)
                            )


class Workout(db.model):
    __tablename__ = "workouts"
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True)

    def __init__(self, name: str, date: datetime, exercises: List[Exercise]):
        self.name = name
        self.date = date
        self.exercises = exercises

    # volume method


class Routine(db.model):
    __tablename__ = "routines"
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=True)
    routine = db.relationship('Routine', backref='user', lazy='dynamic')

    def __init__(self, name: str, date: datetime, workouts: List[Workout]):
        self.name = name
        self.date = date
        self.workouts = workouts

# class User(db.Model, UserMixin):
#     __tablename__ = "users"
#     id = db.Column(db.Integer, primary_key=True)
#     username = db.Column(db.String(80), unique=True)
#     email = db.Column(db.String(120), unique=True)
#     #routine = db.relationship('Routine', backref='user', lazy='dynamic')
#     password_hash = db.Column(db.String)
#
#
# tags = db.Table('tags',
#     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True),
#     db.Column('page_id', db.Integer, db.ForeignKey('page.id'), primary_key=True)
# )
#
# class Page(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     tags = db.relationship('Tag', secondary=tags, lazy='subquery',
#         backref=db.backref('pages', lazy=True))
#
# class Tag(db.Model):
#     id = db.Column(db.Integer, primary_key=True)

Swoletrics/swoletrics/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_debugtoolbar import DebugToolbarExtension

from .config import config_by_name

db = SQLAlchemy()


# Configure authentication
login_manager = LoginManager()
login_manager.session_protection = "strong"
login_manager.login_view = "auth.login"

toolbar = DebugToolbarExtension()


def create_app(config_name):

    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])
    db.init_app(app)
    login_manager.init_app(app)
    toolbar.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='/')

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .routines import routines as routines_blueprint
    app.register_blueprint(routines_blueprint, url_prefix='/routines')

    return app

Swoletrics/swoletrics/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

Swoletrics/swoletrics/main/views.py
from flask import render_template, redirect, url_for, flash
from flask_login import login_required

from . import main
from .. import login_manager
from ..models import User
from ..auth.forms import SignupForm
from .. import db


@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))

@main.route('/index', methods = ["GET", "POST"])
@main.route('/', methods = ["GET", "POST"])
def index():
    form = SignupForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash(f"Welcome, {user.username}! Please login.")
        return redirect(url_for('auth.login'))
    return render_template("index.html", form=form)

@login_required
@main.route('/user/<username>', methods = ["GET", "POST"])
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user = user)

# @main.app_errorhandler(403)
# def forbidden(e):
#     return render_template('403.html'), 403
#

@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

Swoletrics/swoletrics/routines/__init__.py
from flask import Blueprint

routines = Blueprint('routines', __name__)

from . import views

Swoletrics/swoletrics/routines/views.py
from . import routines
from flask import render_template, redirect, url_for, flash
from flask_login import login_required

from ..main import views
from .. import login_manager
from ..models import User


@login_required
@routines.route('/<username>', methods=["GET", "POST"])
def routines(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('routines.html', user=user)

Swoletrics/swoletrics/templates/base.html
<!DOCTYPE html>
<html > <!-- class="no-js" -->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
<!--        <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.min.css') }}">-->
        <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.5/build/pure-min.css"
              integrity="sha384-LTIDeidl25h2dPxrB2Ekgc9c7sEC3CWGM6HeFmuDNUjX76Ert4Z4IY714dhZHPLd"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
        <link rel="stylesheet" href="/static/css/styles.css">
        <script src="../static/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.5/build/grids-responsive-min.css" />

    </head>
    <body>


        <div>

            <header >

                <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">

                    <a class="pure-menu-heading" href="{{ url_for('main.index') }}">Swoletrics</a>


                    <ul class="pure-menu-list">

                        {% if current_user.is_authenticated %}

                            <li class="pure-menu-item "><a href = "{{url_for('routines.routines',username=current_user.username )}}" class="pure-menu-link"> My Routines </a></li>
                            <li class="pure-menu-item "><a href="" class="pure-menu-link"> My Progression </a></li>
                            <li class="pure-menu-item ">
                                <a href="{{url_for('main.user',username=current_user.username)}}"class="pure-menu-link">
                                    {{current_user.username}}'s Home</a></li>
                            <li class="pure-menu-item ">
                                <a href="{{ url_for('auth.logout') }}" class="pure-menu-link">Sign out</a></li>
                        {% else %}
                            <li class="pure-menu-item ">
                                <a href="{{ url_for('main.index')}}" class="pure-menu-link">Home</a></li>
                            <li class="pure-menu-item ">
                                <a href="{{url_for('auth.signup')}}" class="pure-menu-link">Sign up</a></li>
                            <li class="pure-menu-item ">
                                <a href="{{url_for('auth.login')}}" class="pure-menu-link">Sign in</a></li>
                        {% endif %}
                    </ul>
                </div>

            </header>

            <br/><br/><br/>
            <header>
                <div>
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            <ul class="pure-menu-list">
                                {% for message in messages %}
                                <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endwith %}
                </div>
            </header>


            <div class="main-container">
                <div class="main wrapper clearfix">

                    {%  block content %}


                    {%  endblock %}

                </div> <!-- #main -->
            </div> <!-- #main-container -->
        </div>

{% block footer %}
        <div class="footer l-box is-center">
<!--             <footer class="wrapper">-->
            Swoletrics WIP by Edwin Baeza
<!--                  </footer >-->
        </div>

{% endblock %}

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery ||
        document.write('<script src="{{ url_for('static', filename='js/vendor/jquery-1.11.0.min.js') }}"><\/script>')
        </script>

    </body>
</html>

Swoletrics/swoletrics/templates/form_macros.html
{% macro render_field(field) %}
    <tr {% if field.errors %} class="error" {% endif %}>
        <td>{{ field.label }}</td>
        <td>{{ field(**kwargs)|safe }}</td>
    </tr>
    <tr class="error" >
     <td></td>
        <td>
            <ul>
                {% for error in field.errors %}
                    <li {% if field.errors %} style="color: red;" {% endif %}> {{ error }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
{% endmacro %}

Swoletrics/swoletrics/templates/index.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Swoletrics -- Welcome
{%  endblock %}

{% block content %}
<article>

        </section>
            <div class="splash-container">
                <div class="splash">
                    <h1 class="splash-head">Embark on your fitness journey</h1>
                    <p class="splash-subhead">Designed with progression in mind
                    </p>
                    <p><a href="https://muscleandstrengthpyramids.com/" class="pure-button pure-button-primary">Learn More</a>
                    <a href="{{url_for('auth.signup')}}" class="pure-button pure-button-primary">Get Started</a></p>
                    </p>

                </div>
            </div>
        <section>



</article>


<div class="content-wrapper">
    <div class="content">
        <h2 class="content-head is-center">Why Swoletrics?</h2>

        <div class="pure-g">
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">

                <h3 class="content-subhead">
                    Learn to progress
                </h3>
                <p>
                    Understand the Principle of Progressive Overload and its ramifications.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    A program tailored <br/> for you
                </h3>
                <p>
                    Workout routines designed for progress.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    Visualize your progress
                </h3>
                <p>
                    Easily analyse your training.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    The way forward
                </h3>
                <p>
                    Generic and inspirational.
                </p>
            </div>

        </div>
    </div>

    <div class="ribbon l-box-lrg pure-g">
<!--        <div class="l-box-lrg is-center pure-u-1 pure-u-md-1-2 pure-u-lg-2-5">
        </div>-->
        <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-3-5">

            <h2 class="content-head content-head-ribbon">Knowledge and tools to propel your lifting.</h2>
<!--
            <p>
                The Swoletrics platfrom
            </p>-->
        </div>
    </div>

    <div class="content">
        <h2 class="content-head is-center">Get Started Today</h2>

        <div class="pure-g">
        <div class="l-box-lrg pure-u-1 pure-u-md-2-5">
            <form class="pure-form pure-form-stacked" method="post">
                {{ form.hidden_tag() }}
                <fieldset>
                    {{ render_field(form.username) }}
                    {{ render_field(form.email) }}
                    {{ render_field(form.password) }}
                    {{ render_field(form.password2) }}
                    <br/>
                    <button type="submit" class="pure-button"> Sign up </button>


                </fieldset>
            </form>
        </div>

            <div class="l-box-lrg pure-u-1 pure-u-md-3-5">
                <h4>Contact Us</h4>
                <p>
                    Edwin Baeza
                </p>

                <h4>More Information</h4>
                <p>
                    The Pyramids
                </p>
            </div>
        </div>

    </div>

{%block footer %}
    <div class="footer l-box is-center">
        <footer class="wrapper">
            <p>Swoletrics WIP by Edwin Baeza<p>
        </footer >
    </div>
{% endblock%}

</div>


{% endblock %}

Swoletrics/swoletrics/templates/login.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Login
{%  endblock %}


{% block content %}

<br/><br/>

    <h2 class="content-head is-center">Login</h2>
    <div class="pure-g">
        <div class="l-box-lrg pure-u-1 pure-u-md-2-5 ">
            <form class="pure-form pure-form-aligned" method="post">
                {{ form.hidden_tag() }}
                <fieldset class="pure-group">

                    {{ render_field(form.username) }}
                    {{ render_field(form.password) }}

                   <label class = "pure-checkbox">   <div style="float: left; display: inline; vertical-align: middle;">Remember Me
                        <input style="float: left; display: inline; " type="checkbox"/> </div>
                   </label>
                    <br/><br/>
                    <div style="clear: both"/>
                    <button type="submit" class="pure-button"> Sign in</button>

                </fieldset>
            </form>
        </div>



        <div class="l-box-lrg pure-u-1 pure-u-md-3-5">
            <h4>Contact Us</h4>
            <p>
                Edwin Baeza
            </p>

            <h4>More Information</h4>
            <p>
                The pyramids
            </p>
        </div>
    </div>

</br>


{% endblock%}

Swoletrics/swoletrics/templates/routines.html
{% extends "base.html" %}


{% block title %}
{{user.username}}'s Routines
{%  endblock %}


{% block content %}
<h1>Routines</h1>

<h2 class="content-head is-center">
    A Beginner Bodybuilding Template
</h2>

<div class="content">
    <div class="pure-g">

        <div class="pure-u-1-1">
            <form class="pure-form pure-form-stacked">
                <fieldset>
                    <legend><h2> Day 1 - Lower</h2></legend>

                    <!-- First Row  -->
                    <div class="pure-u-1-4">
                        <h4> Exercise</h4>
                    </div>

                    <div class="pure-u-1-6">
                        <h4> Sets</h4>
                    </div>
                    <div class="pure-u-1-6">
                        <h4> Reps</h4>
                    </div>

                    <div class="pure-u-1-6">
                        <h4> %1RM </h4>
                    </div>

                    <div class="pure-u-1-6">
                        <h4> 1st Set RPE </h4>
                    </div>


                    <!-- Second Row  -->
                    <div class="pure-u-1-4">
                        <select name = "Leg Exercises">
                            <optgroup label="Squat Variant" >
                                <option>Low-Bar Back Squat</option>
                                <option>High-Bar Back Squat</option>
                                <option>Front Squat</option>
                                <option>Hack Squat</option>
                            </optgroup>
                        </select>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> 3 </h5>
                    </div>
                    <div class="pure-u-1-6">
                        <h5> 5 </h5>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> 82.5% </h5>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> NA</h5>
                    </div>


                    <!-- Third Row  -->
                    <div class="pure-u-1-4">
                        <select name = "Leg Exercises">
                            <optgroup label = "Deadlift Variant">
                                <option> Conventional Deadlift </option>
                                <option> Sumo Deadlift </option>
                                <option> Romanian DeadliftL</option>
                                <option> Stiff-leg Deadlift</option>
                                <option> Good Morning </option>
                            </optgroup>
                        </select>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> 3 </h5>
                    </div>
                    <div class="pure-u-1-6">
                        <h5> 5 </h5>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> 82.5% </h5>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> NA</h5>
                    </div>


                    <!-- Fourth Row  -->
                    <div class="pure-u-1-4">
                        <select name = "Leg Exercises">
                            <optgroup label="Single Leg Squat Variant ">
                                <option> Bulgarian Split Squat </option>
                                <option> Lunge </option>
                                <option> Step-Ups </option>
                                <option> Single-leg Squat </option>

                            </optgroup>
                        </select>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> 3 </h5>
                    </div>
                    <div class="pure-u-1-6">
                        <h5> 8 </h5>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> NA </h5>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> 8 </h5>
                    </div>


                    <!-- Fifth Row  -->
                    <div class="pure-u-1-4">
                        <select name = "Leg Exercises">
                            <optgroup label="Standing Calf">
                                <option>Deadlift (DL)</option>
                                <option>Romanian DL</option>
                                <option>Stiff-leg DL</option>
                            </optgroup>
                        </select>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> 4 </h5>
                    </div>
                    <div class="pure-u-1-6">
                        <h5> 8 </h5>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> NA </h5>
                    </div>

                    <div class="pure-u-1-6">
                        <h5> 8 </h5>
                    </div>


                </fieldset>
            </form>
        </div>


    </div>
</div>






{% endblock %}

Swoletrics/swoletrics/templates/signup.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Signup
{%  endblock %}


{% block content %}

<br/><br/><br/>
<div class="content">
    <h2 class="content-head is-center"> Knowledge and tools to propel your lifting </h2>

    <div class="ribbon l-box-lrg pure-g">
        <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-3-5">

            <h2 class="content-head content-head-ribbon"> Built around progression </h2>

            <p>
                Some info
            </p>
        </div>
    </div>


    <h2 class="content-head is-center">Sign up here.</h2>


    <div class="pure-g">
        <div class="l-box-lrg pure-u-1 pure-u-md-2-5">
            <form class="pure-form pure-form-stacked" method="post">
                {{ form.hidden_tag() }}
                <fieldset>
                    {{ render_field(form.username) }}
                    {{ render_field(form.email) }}
                    {{ render_field(form.password) }}
                    {{ render_field(form.password2) }}
                    <br/>
                    <button type="submit" class="pure-button"> Sign up </button>
                </fieldset>
            </form>
        </div>


        <div class="l-box-lrg pure-u-1 pure-u-md-3-5">
            <h4>Contact Us</h4>
            <p>
                Edwin Baeza
            </p>

            <h4>More Information</h4>
            <p>
                The pyramids
            </p>
        </div>
    </div>
</div>

</br>
{% endblock%}

Swoletrics/swoletrics/templates/user.html
{% extends "base.html" %}


{% block title %}
{{user.username}}'s page
{%  endblock %}



{% block content %}
<h2 class="content-head is-center">Welcome {{user.username}} </h2>
<article>


<div class="banner"></div>

<div class="l-content">
    <div class="pricing-tables pure-g">

        <div class="pure-u-1 pure-u-md-1-3">
            <div class="pricing-table pricing-table-enterprise">
                <div class="pricing-table-header">
                    <h2> </h2>
                    <span class="pricing-table-price">
                        <span> Knowledge </span>
                    </span>
                </div>

                <a href="https://muscleandstrengthpyramids.com/">
                    <button class="button-choose pure-button">Lean More Here</button>
                </a>
            </div>
        </div>

        <div class="pure-u-1 pure-u-md-1-3">
            <div class="pricing-table pricing-table-enterprise">
                <div class="pricing-table-header">
                    <h2> </h2>

                    <span class="pricing-table-price">
                        <span>Routines</span>
                    </span>
                </div>

                <a href = "{{url_for('routines.routines',username=user.username )}}">
                    <button class="button-choose pure-button"> Create or Edit</button>
                </a>
            </div>
        </div>

        <div class="pure-u-1 pure-u-md-1-3">
            <div class="pricing-table pricing-table-enterprise">
                <div class="pricing-table-header">
                    <h2> </h2>
                    <span class="pricing-table-price">
                        <span> Progression</span>
                    </span>
                </div>

                <a href = "">
                    <button class="button-choose pure-button">See Your results</button>
                </a>
            </div>
        </div>




    </div>



    <div class="information pure-g">

        <div class="pure-u-1 pure-u-md-1-2">
            <div class="l-box">
                <h3 class="information-head"></h3>
                <p>
                </p>
            </div>
        </div>
    </div>
</div>
</article>
{% endblock %}